application: timemachine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /crossdomain\.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml
- url: /favicon\.ico
  static_files: favicon/favicon.ico
  upload: favicon/favicon.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
